In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a[-1]

np.int64(4)

In [7]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
c=b.copy()
c

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9])

In [8]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b[6]=12
c

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9])

In [14]:
d

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9])

In [15]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
c=np.array([13,14,15])
np.concatenate((a,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5]), array([ 6, 12,  8,  9])]

In [18]:
np.where(d==4)

(array([3]),)

In [19]:
np.where(d%2==0)

(array([1, 3, 5, 6, 7]),)

In [20]:
c=np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [21]:
c=np.array([[2,3,1,5],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 5],
       [1, 2, 4, 5]])

In [22]:
c=np.array(['apple','orange','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [23]:
np.random.randint(100)

96

In [25]:
np.random.rand(10)

array([0.39866837, 0.96265924, 0.62482854, 0.47453486, 0.59158299,
       0.99001738, 0.15261366, 0.46884359, 0.00591348, 0.20331556])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])